### ISSUE TITLE
Uncaught TypeError: Cannot set property 'defaults' of undefined     at svg.pathhandles.js:170

### ISSUE THREAD

**Issue by dotnetCarpenter** [Fuzzyma/svg.pathhandles.js#1]
svg.pathhandles.js line 179 (SVG.Element.prototype.**selectize** is undefined):
```js
SVG.Element.prototype.selectize.defaults = {
```

SVG.js: 2.3.6
svg.pathhandles.js: 0.0.1

**Comment by dotnetCarpenter** [comment]
@Fuzzyma Looks like you just need to publish a new version via `git tag v0.0.2 && git push --tag`

**Comment by Fuzzyma** [comment]
You are correct! Will do that when I am back from the dentist ;)

**Comment by Fuzzyma** [comment]
done
